joint_limits:
  arm1_1_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  arm1_2_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  arm2_1_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  arm2_2_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  arm3_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  arm4_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  gripper_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 0
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  head_camera_pan_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0
  head_camera_tilt_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 0.57
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: true
    max_acceleration: 4.0