sobit_pro_pose:

    - { 
        pose_name: "initial_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: -1.57,
        arm_elbow_upper_1_tilt_joint: 1.57,
        arm_elbow_upper_2_tilt_joint: -1.57,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: -1.57,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - {
        pose_name: "detecting_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: -1.57,
        arm_elbow_upper_1_tilt_joint: 1.57,
        arm_elbow_upper_2_tilt_joint: -1.57,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: 0.00,
        hand_joint: -1.0,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: -0.7
    }

    - { 
        pose_name: "grasp_high_pose",
        arm_shoulder_1_tilt_joint: 1.0,
        arm_shoulder_2_tilt_joint: -1.0,
        arm_elbow_upper_1_tilt_joint: 1.0,
        arm_elbow_upper_2_tilt_joint: -1.0,
        arm_elbow_lower_tilt_joint: -1.0,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: -1.0,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - { 
        pose_name: "put_high_pose",
        arm_shoulder_1_tilt_joint: 1.0,
        arm_shoulder_2_tilt_joint: -1.0,
        arm_elbow_upper_1_tilt_joint: 1.0,
        arm_elbow_upper_2_tilt_joint: -1.0,
        arm_elbow_lower_tilt_joint: -1.0,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: -1.0,
        hand_joint: -1.57,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - {
        pose_name: "put_detecting_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: -1.57,
        arm_elbow_upper_1_tilt_joint: 1.57,
        arm_elbow_upper_2_tilt_joint: -1.57,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: -1.57,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: -0.7
    }

    - { 
        pose_name: "grasp2initial_perpendicular_high_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: 0.00,
        arm_elbow_upper_1_tilt_joint: 0.00,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: -1.57,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - { 
        pose_name: "grasp2initial_perpendicular_middle_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: 0.00,
        arm_elbow_upper_1_tilt_joint: -1.57,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: 0.00,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - { 
        pose_name: "grasp2initial_perpendicular_low_pose",
        arm_shoulder_1_tilt_joint: 0.00,
        arm_shoulder_2_tilt_joint: 0.00,
        arm_elbow_upper_1_tilt_joint: -1.57,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: 0.00,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: 0.00,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - { 
        pose_name: "grasp2initial_parallel_high_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: 0.00,
        arm_elbow_upper_1_tilt_joint: 0.00,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: 0.00,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - { 
        pose_name: "grasp2initial_parallel_middle_pose",
        arm_shoulder_1_tilt_joint: 1.57,
        arm_shoulder_2_tilt_joint: 0.00,
        arm_elbow_upper_1_tilt_joint: -1.57,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: -1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: 1.57,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }

    - { 
        pose_name: "grasp2initial_parallel_low_pose",
        arm_shoulder_1_tilt_joint: 0.00,
        arm_shoulder_2_tilt_joint: 0.00,
        arm_elbow_upper_1_tilt_joint: -1.57,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: 1.57,
        arm_elbow_lower_pan_joint: 0.00,
        arm_wrist_tilt_joint: -1.0,
        hand_joint: 0.00,
        head_camera_pan_joint: 0.00,
        head_camera_tilt_joint: 0.0
    }
    
    - { 
        pose_name: "grasp_on_floor_pose",
        arm_shoulder_1_tilt_joint: -1.30,
        arm_shoulder_2_tilt_joint: 1.30,
        arm_elbow_upper_1_tilt_joint: 0.00,
        arm_elbow_upper_2_tilt_joint: 0.00,
        arm_elbow_lower_tilt_joint: 0.00,
        arm_wrist_tilt_joint: -0.25,
        hand_joint: -1.57,
        head_camera_pan_joint: 0.0,
        head_camera_tilt_joint: -0.7
    }
