hardware:
  publish_rate: &loop_hz 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_hz

steer_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: &robot_steer_joints
    - wheel_f_l_steer_joint
    - wheel_f_r_steer_joint
    - wheel_b_l_steer_joint
    - wheel_b_r_steer_joint
  allow_partial_joints_goal: true

wheel_trajectory_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: &robot_wheel_joints
    - wheel_f_l_drive_joint
    - wheel_f_r_drive_joint
    - wheel_b_l_drive_joint
    - wheel_b_r_drive_joint
