hardware:
  publish_rate: &loop_hz 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_hz

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: &robot_arm_joints
    - arm_shoulder_1_tilt_joint
    # - arm_shoulder_2_tilt_joint
    - arm_elbow_upper_1_tilt_joint
    # - arm_elbow_upper_2_tilt_joint
    - arm_elbow_lower_tilt_joint
    - arm_elbow_lower_pan_joint
    - arm_wrist_tilt_joint
    - hand_joint
  allow_partial_joints_goal: true
